'use strict';
// Custos cue parser. One place for the rules that the cue workflows each
// re-implement: who may give a cue, which text counts, and what a cue is.
// Plan: docs/plans/202610070939-cue-sigil-and-living-observation-plan.md
//
// A workflow calls it after a checkout:
//   const { parseComment } = require('./.github/scripts/cue-parser.js');
//   const r = parseComment(comment.body, {
//     association: comment.author_association, authorType: comment.user.type });
//
// Two forms are read, both only at the start of a line (up to three spaces in):
//   ^<navigo> [<conversation-id>] <cue words>     the caret form, case-insensitive
//   @claude <cue words>                           the older form, kept for now
// The caret form is the process cue. The older form stays during the transition.
//
// This module only reads text. It never labels, seals or merges.

const DEFAULT_NAMES = ['claude', 'chatgpt', 'gemini', 'perplexity', 'unexusi', 'custos'];
const ACTIONS = ['recensio', 'probatio', 'lustratio', 'judicium', 'novissimum', 'cursus'];
const MODIFIERS = ['prima', 'ultima', 'suprema', 'extrema', 'renovata', 'expeditus'];
const VERBS = ['disponi', 'petitio', 'placet', 'finalize', 'check', 'concordance', 'sync-labels'];
// 3 to 12 characters after the dash, the same bound tools/session_id.sh check_own enforces
// (minted IDs are always 6; a hand-typed ID may be shorter or longer).
const ID_RE = /^(exp|set|con|oth)-[a-z0-9]{3,12}$/i;
const FOOTER = 'Generated by [Claude Code]';

const cap = (w) => w.charAt(0).toUpperCase() + w.slice(1);

// Drop what is quoted rather than given: fenced code, inline code, > quotes
// and indented code. An unterminated fence runs to the end of the comment.
function strip(body) {
  return body
    .replace(/\r\n?/g, '\n')
    .replace(/```[\s\S]*?(```|$)/g, '\n')
    .replace(/~~~[\s\S]*?(~~~|$)/g, '\n')
    .replace(/`[^`\n]*`/g, ' ')
    .split('\n')
    .filter((line) => !/^\s*>/.test(line) && !/^( {4,}|\t)/.test(line))
    .join('\n');
}

// Read the words after the navigo name: an optional conversation id, then cue words.
function readWords(rest) {
  const tokens = rest.split(/\s+/)
    .map((t) => t.replace(/[.,;:!?]+$/, ''))
    .filter(Boolean);
  let id = null;
  if (tokens.length && ID_RE.test(tokens[0])) id = tokens.shift().toLowerCase();
  if (!tokens.length) return { id, error: 'no cue words' };

  const words = tokens.map((t) => t.toLowerCase());
  const bad = words.filter((w) => !ACTIONS.includes(w) && !MODIFIERS.includes(w) && !VERBS.includes(w));
  if (bad.length) return { id, error: `unrecognized words: ${bad.join(', ')}` };

  const actions = words.filter((w) => ACTIONS.includes(w));
  const modifiers = words.filter((w) => MODIFIERS.includes(w));
  const verbs = words.filter((w) => VERBS.includes(w));

  if (verbs.length === 1 && actions.length === 0 && modifiers.length === 0) {
    return { id, verb: verbs[0], canonical: verbs[0], modifiers: [], action: null };
  }
  if (actions.length === 1 && verbs.length === 0) {
    return {
      id, verb: null, action: cap(actions[0]),
      modifiers: modifiers.map(cap), canonical: words.map(cap).join(' '),
    };
  }
  return { id, error: 'ambiguous cue' };
}

function parseComment(body, opts) {
  const o = opts || {};
  const names = (o.names || DEFAULT_NAMES).map((n) => n.toLowerCase());
  const out = { cues: [], rejected: [], skipped: null };

  if (!body || !String(body).trim()) { out.skipped = 'empty'; return out; }
  if (o.authorType === 'Bot') { out.skipped = 'bot'; return out; }
  if (o.association !== undefined && !(o.allowed || ['OWNER']).includes(o.association)) {
    out.skipped = 'not owner';
    return out;
  }
  if (String(body).includes(FOOTER)) { out.skipped = 'footer'; return out; }

  strip(String(body)).split('\n').forEach((line, i) => {
    const caret = line.match(/^ {0,3}\^([A-Za-z][A-Za-z0-9_-]*)(?![A-Za-z0-9_-])(.*)$/);
    const at = !caret && line.match(/^ {0,3}@(claude)(?![A-Za-z0-9_-])(.*)$/i);
    const m = caret || at;
    if (!m) return;

    const sigil = caret ? '^' : '@';
    const navigo = m[1].toLowerCase();
    if (!names.includes(navigo)) {
      out.rejected.push({ line: i + 1, sigil, navigo, reason: 'unknown navigo' });
      return;
    }
    const read = readWords(m[2]);
    if (read.error) {
      out.rejected.push({ line: i + 1, sigil, navigo, reason: read.error });
      return;
    }
    out.cues.push({
      line: i + 1, sigil, navigo, id: read.id,
      action: read.action, modifiers: read.modifiers, verb: read.verb, canonical: read.canonical,
    });
  });
  return out;
}

module.exports = { parseComment, strip, DEFAULT_NAMES, ACTIONS, MODIFIERS, VERBS };
