#!/usr/bin/env bash
# Peer Inventory — compares two repos' files by git blob id and reports what is
# the same, what differs, and what exists on only one side.
#
# Report-only. Never writes to either repo. Facts only: deciding what a
# difference means is the peer review's job (docs/peer-review-process.md).
#
# Usage: tools/peer_inventory.sh <repoA[@ref]> <repoB[@ref]> [area ...]
#   repo   path to a git checkout; ref defaults to origin/main, else HEAD
#   area   path prefix to compare, or "." for root-level files only
#          (default: . .github .github/workflows .github/ISSUE_TEMPLATE tools docs)
set -euo pipefail

if [[ $# -lt 2 ]]; then
  echo "Usage: $0 <repoA[@ref]> <repoB[@ref]> [area ...]" >&2
  exit 2
fi

SPEC_A="$1"; SPEC_B="$2"; shift 2
AREAS=("$@")
if [[ ${#AREAS[@]} -eq 0 ]]; then
  AREAS=("." ".github" ".github/workflows" ".github/ISSUE_TEMPLATE" "tools" "docs")
fi

TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

resolve() { # spec -> "path ref label"
  local spec="$1" path ref
  path="${spec%%@*}"
  if [[ "$spec" == *@* ]]; then ref="${spec#*@}"; else ref=""; fi
  if [[ ! -d "$path" ]] || ! git -C "$path" rev-parse --git-dir >/dev/null 2>&1; then
    echo "ERROR: '$path' is not a git checkout." >&2; exit 2
  fi
  if [[ -z "$ref" ]]; then
    if git -C "$path" rev-parse --verify -q origin/main >/dev/null; then ref="origin/main"; else ref="HEAD"; fi
  fi
  git -C "$path" rev-parse --verify -q "$ref" >/dev/null || { echo "ERROR: ref '$ref' not found in '$path'." >&2; exit 2; }
  echo "$(cd "$path" && pwd) $ref $(basename "$(cd "$path" && pwd)")"
}

# resolve runs in a subshell, so its failure must be caught here or the script
# would carry on with empty values.
RES_A="$(resolve "$SPEC_A")" || exit 2
RES_B="$(resolve "$SPEC_B")" || exit 2
read -r PA RA LA <<<"$RES_A"
read -r PB RB LB <<<"$RES_B"

# blob-id<TAB>path for every file at the ref, sorted by path
manifest() { git -C "$1" ls-tree -r "$2" | awk -F'\t' '{split($1,m," "); print $2 "\t" m[3]}' | LC_ALL=C sort; }
manifest "$PA" "$RA" >"$TMP/a"
manifest "$PB" "$RB" >"$TMP/b"

in_area() { # area -> awk filter on path (field 1)
  local area="$1"
  if [[ "$area" == "." ]]; then awk -F'\t' '$1 !~ /\//'
  else awk -F'\t' -v p="${area%/}/" 'index($1,p)==1 && substr($1,length(p)+1) !~ /\//'
  fi
}

echo "# Peer inventory"
echo
echo "- A: **$LA** @ \`$RA\`"
echo "- B: **$LB** @ \`$RB\`"
echo "- Compared by git blob id: \"same\" means byte-identical."
echo

for area in "${AREAS[@]}"; do
  in_area "$area" <"$TMP/a" >"$TMP/aa"
  in_area "$area" <"$TMP/b" >"$TMP/bb"
  # shellcheck disable=SC2016
  same=$(join -t $'\t' "$TMP/aa" "$TMP/bb" | awk -F'\t' '$2==$3' | cut -f1)
  diff_=$(join -t $'\t' "$TMP/aa" "$TMP/bb" | awk -F'\t' '$2!=$3' | cut -f1)
  only_a=$(join -t $'\t' -v1 "$TMP/aa" "$TMP/bb" | cut -f1)
  only_b=$(join -t $'\t' -v2 "$TMP/aa" "$TMP/bb" | cut -f1)
  count() { if [[ -z "$1" ]]; then echo 0; else printf '%s\n' "$1" | wc -l | tr -d ' '; fi; }
  echo "## \`$area\`"
  echo
  echo "same: $(count "$same") · differs: $(count "$diff_") · only $LA: $(count "$only_a") · only $LB: $(count "$only_b")"
  echo
  show() { # label list
    [[ -z "$2" ]] && return
    echo "**$1**"
    printf '%s\n' "$2" | sed 's/^/- `/; s/$/`/'
    echo
  }
  show "Differs (same path, different content)" "$diff_"
  show "Only in $LA" "$only_a"
  show "Only in $LB" "$only_b"
done

echo "<sub>Generated by tools/peer_inventory.sh. Report-only; no repo was modified.</sub>"
