'use strict';
// Offline test table for .github/scripts/cue-parser.js. No network, no GitHub.
// Run: bash tools/test_cue_parser.sh

const { parseComment, DEFAULT_NAMES } = require('../.github/scripts/cue-parser.js');

const FOOTER = '\n\n---\n_Generated by [Claude Code](https://claude.ai/code)_';
const OWNER = { association: 'OWNER', authorType: 'User' };

// Each row: name, comment body, options, and what the parse must show.
// want.cues is a list of [sigil, navigo, canonical, id]; want.rejected is a list of reasons.
const rows = [
  ['caret seal cue', '^claude ultima probatio', OWNER, { cues: [['^', 'claude', 'Ultima Probatio', null]] }],
  ['case-insensitive caret', '^Claude Ultima Probatio', OWNER, { cues: [['^', 'claude', 'Ultima Probatio', null]] }],
  ['other navigo', '^chatgpt prima recensio', OWNER, { cues: [['^', 'chatgpt', 'Prima Recensio', null]] }],
  ['custos verb', '^custos check', OWNER, { cues: [['^', 'custos', 'check', null]] }],
  ['custos concordance', '^custos concordance', OWNER, { cues: [['^', 'custos', 'concordance', null]] }],
  ['conversation id', '^gemini set-4f2a1c disponi', OWNER, { cues: [['^', 'gemini', 'disponi', 'set-4f2a1c']] }],
  ['modifier after action', '^claude cursus expeditus', OWNER, { cues: [['^', 'claude', 'Cursus Expeditus', null]] }],
  ['modifier renovata', '^claude recensio renovata', OWNER, { cues: [['^', 'claude', 'Recensio Renovata', null]] }],
  ['verb finalize', '^claude finalize', OWNER, { cues: [['^', 'claude', 'finalize', null]] }],
  ['verb sync-labels', '^custos sync-labels', OWNER, { cues: [['^', 'custos', 'sync-labels', null]] }],
  ['trailing punctuation', '^claude ultima probatio.', OWNER, { cues: [['^', 'claude', 'Ultima Probatio', null]] }],
  ['crlf line endings', '^claude ultima probatio\r\n', OWNER, { cues: [['^', 'claude', 'Ultima Probatio', null]] }],
  ['second line of a comment', 'Looks good.\n^claude ultima probatio', OWNER, { cues: [['^', 'claude', 'Ultima Probatio', null]] }],
  ['three spaces in', '   ^claude ultima probatio', OWNER, { cues: [['^', 'claude', 'Ultima Probatio', null]] }],
  ['two cues, two lines', '^claude prima recensio\n^chatgpt ultima recensio', OWNER,
    { cues: [['^', 'claude', 'Prima Recensio', null], ['^', 'chatgpt', 'Ultima Recensio', null]] }],
  ['older at form', '@claude ultima probatio', OWNER, { cues: [['@', 'claude', 'Ultima Probatio', null]] }],
  ['older at finalize', '@claude finalize', OWNER, { cues: [['@', 'claude', 'finalize', null]] }],
  ['at and caret together', '@claude finalize\n^custos check', OWNER,
    { cues: [['@', 'claude', 'finalize', null], ['^', 'custos', 'check', null]] }],

  // Not cues: quoted, mid-sentence, or not at the start of a line.
  ['mid-sentence caret', 'I think ^claude ultima probatio is fine', OWNER, { cues: [] }],
  ['mid-sentence at', 'thanks @claude finalize', OWNER, { cues: [] }],
  ['inline code', 'use `^claude ultima probatio` to seal', OWNER, { cues: [] }],
  ['fenced code', '```\n^claude ultima probatio\n```', OWNER, { cues: [] }],
  ['unterminated fence', 'text\n```\n^claude ultima probatio', OWNER, { cues: [] }],
  ['quoted line', '> ^claude ultima probatio', OWNER, { cues: [] }],
  ['indented code', '    ^claude ultima probatio', OWNER, { cues: [] }],
  ['tab-indented code', '\t^claude ultima probatio', OWNER, { cues: [] }],
  ['caret then space', '^ claude ultima probatio', OWNER, { cues: [] }],
  ['regex anchor', '^[a-z]+$', OWNER, { cues: [] }],
  ['number after caret', '^2 is the exponent', OWNER, { cues: [] }],

  // Looks like a cue but is not one: reported as rejected, never as a cue.
  ['unknown navigo', '^bob ultima probatio', OWNER, { cues: [], rejected: ['unknown navigo'] }],
  ['navigo alone', '^claude', OWNER, { cues: [], rejected: ['no cue words'] }],
  ['navigo and id only', '^claude set-4f2a1c', OWNER, { cues: [], rejected: ['no cue words'] }],
  ['talk after the name', '^claude is great', OWNER, { cues: [], rejected: ['unrecognized words: is, great'] }],
  ['regex that names a navigo', '^claude.*', OWNER, { cues: [], rejected: ['unrecognized words: .*'] }],
  ['two actions', '^claude probatio recensio', OWNER, { cues: [], rejected: ['ambiguous cue'] }],
  ['verb with a modifier', '^claude ultima finalize', OWNER, { cues: [], rejected: ['ambiguous cue'] }],
  ['modifier only', '^claude ultima', OWNER, { cues: [], rejected: ['ambiguous cue'] }],

  // Who may give a cue.
  ['footer comment', `^claude ultima probatio${FOOTER}`, OWNER, { cues: [], skipped: 'footer' }],
  ['member, not owner', '^claude ultima probatio', { association: 'MEMBER', authorType: 'User' }, { cues: [], skipped: 'not owner' }],
  ['collaborator', '^claude ultima probatio', { association: 'COLLABORATOR', authorType: 'User' }, { cues: [], skipped: 'not owner' }],
  ['bot author', '^claude ultima probatio', { association: 'OWNER', authorType: 'Bot' }, { cues: [], skipped: 'bot' }],
  ['allowed set widened', '^claude ultima probatio', { association: 'MEMBER', allowed: ['OWNER', 'MEMBER'] },
    { cues: [['^', 'claude', 'Ultima Probatio', null]] }],
  ['no association given', '^claude ultima probatio', {}, { cues: [['^', 'claude', 'Ultima Probatio', null]] }],
  ['empty body', '', OWNER, { cues: [], skipped: 'empty' }],
  ['whitespace body', '  \n ', OWNER, { cues: [], skipped: 'empty' }],
  ['custom name list', '^bob ultima probatio', { names: ['bob'] }, { cues: [['^', 'bob', 'Ultima Probatio', null]] }],
];

let failed = 0;
const say = (text) => process.stdout.write(`${text}\n`);
const fail = (name, msg) => { failed += 1; say(`FAIL ${name}: ${msg}`); };

for (const [name, body, opts, want] of rows) {
  const got = parseComment(body, opts);
  const gotCues = got.cues.map((c) => [c.sigil, c.navigo, c.canonical, c.id]);
  if (JSON.stringify(gotCues) !== JSON.stringify(want.cues)) {
    fail(name, `cues ${JSON.stringify(gotCues)} != ${JSON.stringify(want.cues)}`);
    continue;
  }
  const gotRej = got.rejected.map((r) => r.reason);
  if (JSON.stringify(gotRej) !== JSON.stringify(want.rejected || [])) {
    fail(name, `rejected ${JSON.stringify(gotRej)} != ${JSON.stringify(want.rejected || [])}`);
    continue;
  }
  if (got.skipped !== (want.skipped || null)) {
    fail(name, `skipped ${got.skipped} != ${want.skipped || null}`);
  }
}

// The registry text arrives in REGISTRY_TEXT (tools/test_cue_parser.sh sets it from docs/navigo-registry.md).
// The default names must be the navigos the registry lists (custos is the workflows' own name).
const registry = (process.env.REGISTRY_TEXT || '').toLowerCase();
for (const n of DEFAULT_NAMES.filter((x) => x !== 'custos')) {
  if (!registry.includes(n)) fail(`registry has ${n}`, 'name not found in docs/navigo-registry.md');
}

const total = rows.length + DEFAULT_NAMES.length - 1;
say(`${total - failed} of ${total} passed`);
process.exit(failed ? 1 : 0);
